// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjnmqn6S0EMEm-E9v9A4QU_aZn3DOqZ6U',
    appId: '1:219204731860:web:d4d62ee255d73347d14c41',
    messagingSenderId: '219204731860',
    projectId: 'gestion-hotel-app-taham5439',
    authDomain: 'gestion-hotel-app-taham5439.firebaseapp.com',
    storageBucket: 'gestion-hotel-app-taham5439.firebasestorage.app',
    measurementId: 'G-M2DSQZ54JX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEDqiKxDcetK9TSR0RszigKg5OcwgIxBE',
    appId: '1:219204731860:android:24b730355d644fccd14c41',
    messagingSenderId: '219204731860',
    projectId: 'gestion-hotel-app-taham5439',
    storageBucket: 'gestion-hotel-app-taham5439.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1-_W9yAya6-OBeaRCv49yVB_9w6JMQpM',
    appId: '1:219204731860:ios:e946bc5c19a224e9d14c41',
    messagingSenderId: '219204731860',
    projectId: 'gestion-hotel-app-taham5439',
    storageBucket: 'gestion-hotel-app-taham5439.firebasestorage.app',
    iosBundleId: 'com.example.gestionHotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1-_W9yAya6-OBeaRCv49yVB_9w6JMQpM',
    appId: '1:219204731860:ios:e946bc5c19a224e9d14c41',
    messagingSenderId: '219204731860',
    projectId: 'gestion-hotel-app-taham5439',
    storageBucket: 'gestion-hotel-app-taham5439.firebasestorage.app',
    iosBundleId: 'com.example.gestionHotel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjnmqn6S0EMEm-E9v9A4QU_aZn3DOqZ6U',
    appId: '1:219204731860:web:30348cbd2e3c26ddd14c41',
    messagingSenderId: '219204731860',
    projectId: 'gestion-hotel-app-taham5439',
    authDomain: 'gestion-hotel-app-taham5439.firebaseapp.com',
    storageBucket: 'gestion-hotel-app-taham5439.firebasestorage.app',
    measurementId: 'G-NLP16PY81F',
  );
}
